# Generated by Django 2.1.7 on 2019-03-30 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('truecaller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserContactsMapping',
            new_name='UserContactMapping',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
