# Generated by Django 2.1.7 on 2019-03-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecaller', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
