# Generated by Django 2.1.7 on 2019-03-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecaller', '0004_auto_20190331_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
